
game_board = ({"property":{"name":"Go","state":0}},
              {"property":{"name":"old kent road","price":60,"state":1,"rent":70}},
              {"property":{"name":"chance","state":2}},
              {"property":{"name":"whitechapel road","price":60,"state":3,"rent":70}},
              {"property":{"name":"chance","state":4}},
              {"property":{"name":"the angel islington","price":100,"state":5,"rent":80}},
              {"property":{"name":"euston road","price":100,"state":6,"rent":80}},
              {"property":{"name":"teleport","state":7}},
              {"property":{"name":"pentonyille","price":100,"state":8,"rent":100}},
              {"property":{"name":"visiting jail","state":9}},
              {"property":{"name":"pall mall","price":140,"state":10,"rent":110}},
              {"property":{"name":"chance","state":11}},
              {"property":{"name":"whitehall","price":140,"state":12,"rent":110}},
              {"property":{"name":"northhumb'nd avenue","price":160,"state":13,"rent":130}},
              {"property":{"name":"bow street","price":180,"state":14,"rent":140}},
              {"property":{"name":"marlborough street","price":180,"state":15,"rent":140}},
              {"property":{"name":"teleport","state":16}},
              {"property":{"name":"vine street","price":200,"state":17,"rent":160}},
              {"property":{"name":"free parking","state":18}},
              {"property":{"name":"strand","price":220,"state":19,"rent":170}},
              {"property":{"name":"chance","state":20}},
              {"property":{"name":"fleet street","price":220,"state":21,"rent":170}},
              {"property":{"name":"trafalgar square","price":240,"state":22,"rent":190}},
              {"property":{"name":"leicester square","price":260,"state":23,"rent":200}},
              {"property":{"name":"conventry street","price":260,"state":24,"rent":200}},
              {"property":{"name":"teleport","state":25}},
              {"property":{"name":"piccadilly","price":280,"state":26,"rent":220}},
              {"property":{"name":"go to jail","state":27}},
              {"property":{"name":"regent street","price":300,"state":28,"rent":230}},
              {"property":{"name":"chance","state":29}},
              {"property":{"name":"oxford street","price":300,"state":30,"rent":230}},
              {"property":{"name":"bond street","price":320,"state":31,"rent":250}},
              {"property":{"name":"chance","state":32}},
              {"property":{"name":"park lane","price":350,"state":33,"rent":270}},
              {"property":{"name":"teleport","state":34}},
              {"property":{"name":"mayfair","price":400,"state":35,"rent":300}}
)

